-- Создание таблицы компании
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(250) NOT NULL,
    budget DECIMAL(15,2) NOT NULL
);

--Создание таблицы компания - сотрудники
CREATE TABLE IF NOT EXISTS company_employees (
    company_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    PRIMARY KEY (company_id, employee_id),
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);